version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: true
  skip-dirs:
    - examples

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - whitespace
    - err113
    - errorlint
    - nilerr
    - gocritic
    - nakedret
    - unconvert
    - dogsled
    - copyloopvar
    - prealloc
    - gosec
    - exhaustive
    - noctx
    - nolintlint
    - promlinter

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - revive
    - path: "examples/"
      linters:
        - revive
        - gosec